import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
    docsSidebar: [
        'intro',
        'quick-start',
        {
            type: 'category',
            label: 'API Reference',
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'api-reference',
                },
            ],
        },
    ],
};

export default sidebars;
